services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db_inventory
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db_inventory:5432/db_inventory
      - SECRET_KEY=minha-chave-secreta-123
  db_inventory:
    image: postgres:16-alpine
    container_name: db_inventory
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_inventory
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: